import {IParkingGraph} from "../../_types/graph/IParkingGraph";

export const lot = {
    "0": {
        x: -2,
        y: 3.5,
        tags: [],
        edges: [
            {
                end: "105",
                tags: ["botPath"],
                distance: 1.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "1": {
        x: 0,
        y: 5.5,
        tags: ["exit"],
        edges: [],
    },
    "2": {
        x: 3,
        y: 0,
        tags: [],
        edges: [
            {
                end: "4",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "60",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "3",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "101",
                tags: ["botPath"],
                distance: 5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "3": {
        x: 3,
        y: 5.5,
        tags: [],
        edges: [
            {
                end: "2",
                tags: ["pedestrianPath", "carPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "1",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 3,
                angle: 3.141592653589793,
            },
            {
                end: "46",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "29",
                tags: ["pedestrianPath"],
                distance: 14,
                angle: 0,
            },
            {
                end: "101",
                tags: ["botPath"],
                distance: 0.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "4": {
        x: 3,
        y: -2.5,
        tags: [],
        edges: [
            {
                end: "5",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "61",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "2",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "5": {
        x: 3,
        y: -5,
        tags: [],
        edges: [
            {
                end: "6",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "55",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "4",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "6": {
        x: 3,
        y: -7.5,
        tags: [],
        edges: [
            {
                end: "7",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "54",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "5",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "7": {
        x: 3,
        y: -10,
        tags: [],
        edges: [
            {
                end: "8",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "11",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "6",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "8": {
        x: 3,
        y: -12.5,
        tags: [],
        edges: [
            {
                end: "9",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "10",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "7",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "9": {
        x: 3,
        y: -15,
        tags: [],
        edges: [
            {
                end: "14",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 14,
                angle: 0,
            },
            {
                end: "8",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "10": {
        x: 7.5,
        y: -12.5,
        tags: ["spot"],
        edges: [
            {
                end: "8",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "12",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 0,
            },
            {
                end: "11",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "11": {
        x: 7.5,
        y: -10,
        tags: ["spot"],
        edges: [
            {
                end: "7",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "52",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 0,
            },
            {
                end: "54",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "10",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "12": {
        x: 12.5,
        y: -12.5,
        tags: ["spot"],
        edges: [
            {
                end: "10",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 3.141592653589793,
            },
            {
                end: "13",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "52",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "13": {
        x: 17,
        y: -12.5,
        tags: [],
        edges: [
            {
                end: "15",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "12",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "20",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "14",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "14": {
        x: 17,
        y: -15,
        tags: [],
        edges: [
            {
                end: "23",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 14,
                angle: 0,
            },
            {
                end: "13",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "9",
                tags: ["pedestrianPath"],
                distance: 14,
                angle: 3.141592653589793,
            },
        ],
    },
    "15": {
        x: 17,
        y: -10,
        tags: [],
        edges: [
            {
                end: "16",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "52",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "74",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "13",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "16": {
        x: 17,
        y: -7.5,
        tags: [],
        edges: [
            {
                end: "17",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "53",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "75",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "15",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "17": {
        x: 17,
        y: -5,
        tags: [],
        edges: [
            {
                end: "18",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "56",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "76",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "16",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "18": {
        x: 17,
        y: -2.5,
        tags: [],
        edges: [
            {
                end: "19",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "57",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "77",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "17",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "19": {
        x: 17,
        y: 0,
        tags: [],
        edges: [
            {
                end: "29",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "58",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "78",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "18",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "20": {
        x: 21.5,
        y: -12.5,
        tags: ["spot"],
        edges: [
            {
                end: "13",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "21",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 0,
            },
            {
                end: "74",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "21": {
        x: 26.5,
        y: -12.5,
        tags: ["spot"],
        edges: [
            {
                end: "20",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 3.141592653589793,
            },
            {
                end: "22",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "73",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "22": {
        x: 31,
        y: -12.5,
        tags: [],
        edges: [
            {
                end: "24",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "21",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "23",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "23": {
        x: 31,
        y: -15,
        tags: [],
        edges: [
            {
                end: "22",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "14",
                tags: ["pedestrianPath"],
                distance: 14,
                angle: 3.141592653589793,
            },
        ],
    },
    "24": {
        x: 31,
        y: -10,
        tags: [],
        edges: [
            {
                end: "25",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "73",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "22",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "25": {
        x: 31,
        y: -7.5,
        tags: [],
        edges: [
            {
                end: "26",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "85",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "24",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "26": {
        x: 31,
        y: -5,
        tags: [],
        edges: [
            {
                end: "27",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "86",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "25",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "27": {
        x: 31,
        y: -2.5,
        tags: [],
        edges: [
            {
                end: "28",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "87",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "26",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "28": {
        x: 31,
        y: 0,
        tags: [],
        edges: [
            {
                end: "30",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "88",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "27",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "29": {
        x: 17,
        y: 5.5,
        tags: [],
        edges: [
            {
                end: "3",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 14,
                angle: 3.141592653589793,
            },
            {
                end: "45",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "19",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "30",
                tags: ["pedestrianPath"],
                distance: 14,
                angle: 0,
            },
        ],
    },
    "30": {
        x: 31,
        y: 5.5,
        tags: [],
        edges: [
            {
                end: "29",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 14,
                angle: 3.141592653589793,
            },
            {
                end: "31",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "28",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "31": {
        x: 31,
        y: 8,
        tags: [],
        edges: [
            {
                end: "33",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "89",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "30",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "32": {
        x: 31,
        y: 13,
        tags: [],
        edges: [
            {
                end: "34",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "91",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "33",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "33": {
        x: 31,
        y: 10.5,
        tags: [],
        edges: [
            {
                end: "32",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "90",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "31",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "34": {
        x: 31,
        y: 15.5,
        tags: [],
        edges: [
            {
                end: "35",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "92",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "32",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "35": {
        x: 31,
        y: 18,
        tags: [],
        edges: [
            {
                end: "36",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "93",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "34",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "36": {
        x: 31,
        y: 20.5,
        tags: [],
        edges: [
            {
                end: "37",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "94",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "35",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "37": {
        x: 31,
        y: 23,
        tags: [],
        edges: [
            {
                end: "38",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 14,
                angle: 3.141592653589793,
            },
            {
                end: "98",
                tags: ["pedestrianPath"],
                distance: 1.5,
                angle: 1.5707963267948966,
            },
            {
                end: "36",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "38": {
        x: 17,
        y: 23,
        tags: [],
        edges: [
            {
                end: "40",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 14,
                angle: 3.141592653589793,
            },
            {
                end: "96",
                tags: ["pedestrianPath"],
                distance: 1.8027756377319946,
                angle: 2.1587989303424644,
            },
            {
                end: "97",
                tags: ["pedestrianPath"],
                distance: 1.8027756377319946,
                angle: 0.982793723247329,
            },
            {
                end: "39",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "37",
                tags: ["pedestrianPath"],
                distance: 14,
                angle: 0,
            },
        ],
    },
    "39": {
        x: 17,
        y: 20.5,
        tags: [],
        edges: [
            {
                end: "38",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "66",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "84",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "41",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "40": {
        x: 3,
        y: 23,
        tags: [],
        edges: [
            {
                end: "51",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "95",
                tags: ["pedestrianPath"],
                distance: 1.5,
                angle: 1.5707963267948966,
            },
            {
                end: "38",
                tags: ["pedestrianPath"],
                distance: 14,
                angle: 0,
            },
        ],
    },
    "41": {
        x: 17,
        y: 18,
        tags: [],
        edges: [
            {
                end: "39",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "65",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "83",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "42",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "42": {
        x: 17,
        y: 15.5,
        tags: [],
        edges: [
            {
                end: "41",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "64",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "82",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "43",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "43": {
        x: 17,
        y: 13,
        tags: [],
        edges: [
            {
                end: "42",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "63",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "81",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "44",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "44": {
        x: 17,
        y: 10.5,
        tags: [],
        edges: [
            {
                end: "43",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "62",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "80",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "45",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "45": {
        x: 17,
        y: 8,
        tags: [],
        edges: [
            {
                end: "44",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "59",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "79",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "29",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "46": {
        x: 3,
        y: 8,
        tags: [],
        edges: [
            {
                end: "3",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "67",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "47",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "47": {
        x: 3,
        y: 10.5,
        tags: [],
        edges: [
            {
                end: "46",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "68",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "48",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "48": {
        x: 3,
        y: 13,
        tags: [],
        edges: [
            {
                end: "47",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "69",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "49",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "49": {
        x: 3,
        y: 15.5,
        tags: [],
        edges: [
            {
                end: "48",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "70",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "50",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "50": {
        x: 3,
        y: 18,
        tags: [],
        edges: [
            {
                end: "49",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "71",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "51",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "51": {
        x: 3,
        y: 20.5,
        tags: [],
        edges: [
            {
                end: "50",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "72",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "40",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "52": {
        x: 12.5,
        y: -10,
        tags: ["spot"],
        edges: [
            {
                end: "11",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 3.141592653589793,
            },
            {
                end: "15",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "12",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "53",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "53": {
        x: 12.5,
        y: -7.5,
        tags: ["spot"],
        edges: [
            {
                end: "54",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 3.141592653589793,
            },
            {
                end: "16",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "52",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "56",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "54": {
        x: 7.5,
        y: -7.5,
        tags: ["spot"],
        edges: [
            {
                end: "6",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "53",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 0,
            },
            {
                end: "55",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "11",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "55": {
        x: 7.5,
        y: -5,
        tags: ["spot"],
        edges: [
            {
                end: "5",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "56",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 0,
            },
            {
                end: "61",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "54",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "56": {
        x: 12.5,
        y: -5,
        tags: ["spot"],
        edges: [
            {
                end: "55",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 3.141592653589793,
            },
            {
                end: "17",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "53",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "57",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "57": {
        x: 12.5,
        y: -2.5,
        tags: ["spot"],
        edges: [
            {
                end: "61",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 3.141592653589793,
            },
            {
                end: "18",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "56",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "58",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "58": {
        x: 12.5,
        y: 0,
        tags: ["spot"],
        edges: [
            {
                end: "60",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 3.141592653589793,
            },
            {
                end: "19",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "57",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "59",
                tags: ["pedestrianPath"],
                distance: 5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "59": {
        x: 12.5,
        y: 8,
        tags: ["spot"],
        edges: [
            {
                end: "67",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 3.141592653589793,
            },
            {
                end: "45",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "58",
                tags: ["pedestrianPath"],
                distance: 5,
                angle: -1.5707963267948966,
            },
            {
                end: "62",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "60": {
        x: 7.5,
        y: 0,
        tags: ["spot"],
        edges: [
            {
                end: "2",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "58",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 0,
            },
            {
                end: "61",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "67",
                tags: ["pedestrianPath"],
                distance: 5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "61": {
        x: 7.5,
        y: -2.5,
        tags: ["spot"],
        edges: [
            {
                end: "4",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "57",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 0,
            },
            {
                end: "60",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "55",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "62": {
        x: 12.5,
        y: 10.5,
        tags: ["spot"],
        edges: [
            {
                end: "68",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 3.141592653589793,
            },
            {
                end: "44",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "59",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "63",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "63": {
        x: 12.5,
        y: 13,
        tags: ["spot"],
        edges: [
            {
                end: "69",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 3.141592653589793,
            },
            {
                end: "43",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "62",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "64",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "64": {
        x: 12.5,
        y: 15.5,
        tags: ["spot"],
        edges: [
            {
                end: "70",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 3.141592653589793,
            },
            {
                end: "42",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "63",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "65",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "65": {
        x: 12.5,
        y: 18,
        tags: ["spot"],
        edges: [
            {
                end: "71",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 3.141592653589793,
            },
            {
                end: "41",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "64",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "66",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "66": {
        x: 12.5,
        y: 20.5,
        tags: ["spot"],
        edges: [
            {
                end: "72",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 3.141592653589793,
            },
            {
                end: "39",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "65",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "67": {
        x: 7.5,
        y: 8,
        tags: ["spot"],
        edges: [
            {
                end: "46",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "59",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 0,
            },
            {
                end: "60",
                tags: ["pedestrianPath"],
                distance: 5,
                angle: -1.5707963267948966,
            },
            {
                end: "68",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "68": {
        x: 7.5,
        y: 10.5,
        tags: ["spot"],
        edges: [
            {
                end: "47",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "62",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 0,
            },
            {
                end: "67",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "69",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "69": {
        x: 7.5,
        y: 13,
        tags: ["spot"],
        edges: [
            {
                end: "48",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "63",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 0,
            },
            {
                end: "68",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "70",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "70": {
        x: 7.5,
        y: 15.5,
        tags: ["spot"],
        edges: [
            {
                end: "49",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "64",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 0,
            },
            {
                end: "69",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "71",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "71": {
        x: 7.5,
        y: 18,
        tags: ["spot"],
        edges: [
            {
                end: "50",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "65",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 0,
            },
            {
                end: "70",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "72",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "72": {
        x: 7.5,
        y: 20.5,
        tags: ["spot"],
        edges: [
            {
                end: "51",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "66",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 0,
            },
            {
                end: "71",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "73": {
        x: 26.5,
        y: -10,
        tags: ["spot"],
        edges: [
            {
                end: "74",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 3.141592653589793,
            },
            {
                end: "24",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "85",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "21",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "74": {
        x: 21.5,
        y: -10,
        tags: ["spot"],
        edges: [
            {
                end: "15",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "73",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 0,
            },
            {
                end: "20",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "75",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "75": {
        x: 21.5,
        y: -7.5,
        tags: ["spot"],
        edges: [
            {
                end: "16",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "85",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 0,
            },
            {
                end: "74",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "76",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "76": {
        x: 21.5,
        y: -5,
        tags: ["spot"],
        edges: [
            {
                end: "17",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "86",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 0,
            },
            {
                end: "75",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "77",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "77": {
        x: 21.5,
        y: -2.5,
        tags: ["spot"],
        edges: [
            {
                end: "18",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "87",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 0,
            },
            {
                end: "76",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "78",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "78": {
        x: 21.5,
        y: 0,
        tags: ["spot"],
        edges: [
            {
                end: "19",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "88",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 0,
            },
            {
                end: "77",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "79",
                tags: ["pedestrianPath"],
                distance: 5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "79": {
        x: 21.5,
        y: 8,
        tags: ["spot"],
        edges: [
            {
                end: "45",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "89",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 0,
            },
            {
                end: "80",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "78",
                tags: ["pedestrianPath"],
                distance: 5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "80": {
        x: 21.5,
        y: 10.5,
        tags: ["spot"],
        edges: [
            {
                end: "44",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "90",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 0,
            },
            {
                end: "81",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "79",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "81": {
        x: 21.5,
        y: 13,
        tags: ["spot"],
        edges: [
            {
                end: "43",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "91",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 0,
            },
            {
                end: "82",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "80",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "82": {
        x: 21.5,
        y: 15.5,
        tags: ["spot"],
        edges: [
            {
                end: "42",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "92",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 0,
            },
            {
                end: "83",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "81",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "83": {
        x: 21.5,
        y: 18,
        tags: ["spot"],
        edges: [
            {
                end: "41",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "93",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 0,
            },
            {
                end: "84",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "82",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "84": {
        x: 21.5,
        y: 20.5,
        tags: ["spot"],
        edges: [
            {
                end: "39",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 3.141592653589793,
            },
            {
                end: "94",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 0,
            },
            {
                end: "83",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "85": {
        x: 26.5,
        y: -7.5,
        tags: ["spot"],
        edges: [
            {
                end: "75",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 3.141592653589793,
            },
            {
                end: "25",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "86",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "73",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "86": {
        x: 26.5,
        y: -5,
        tags: ["spot"],
        edges: [
            {
                end: "76",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 3.141592653589793,
            },
            {
                end: "26",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "87",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "85",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "87": {
        x: 26.5,
        y: -2.5,
        tags: ["spot"],
        edges: [
            {
                end: "77",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 3.141592653589793,
            },
            {
                end: "27",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "88",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "86",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "88": {
        x: 26.5,
        y: 0,
        tags: ["spot"],
        edges: [
            {
                end: "78",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 3.141592653589793,
            },
            {
                end: "28",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "89",
                tags: ["pedestrianPath"],
                distance: 5,
                angle: 1.5707963267948966,
            },
            {
                end: "87",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "89": {
        x: 26.5,
        y: 8,
        tags: ["spot"],
        edges: [
            {
                end: "79",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 3.141592653589793,
            },
            {
                end: "31",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "90",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
            {
                end: "88",
                tags: ["pedestrianPath"],
                distance: 5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "90": {
        x: 26.5,
        y: 10.5,
        tags: ["spot"],
        edges: [
            {
                end: "80",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 3.141592653589793,
            },
            {
                end: "33",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "89",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "91",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "91": {
        x: 26.5,
        y: 13,
        tags: ["spot"],
        edges: [
            {
                end: "81",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 3.141592653589793,
            },
            {
                end: "32",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "90",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "92",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "92": {
        x: 26.5,
        y: 15.5,
        tags: ["spot"],
        edges: [
            {
                end: "82",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 3.141592653589793,
            },
            {
                end: "34",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "91",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "93",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "93": {
        x: 26.5,
        y: 18,
        tags: ["spot"],
        edges: [
            {
                end: "83",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 3.141592653589793,
            },
            {
                end: "35",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "92",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
            {
                end: "94",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: 1.5707963267948966,
            },
        ],
    },
    "94": {
        x: 26.5,
        y: 20.5,
        tags: ["spot"],
        edges: [
            {
                end: "84",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 5,
                angle: 3.141592653589793,
            },
            {
                end: "36",
                tags: ["pedestrianPath", "carPath", "botPath"],
                distance: 4.5,
                angle: 0,
            },
            {
                end: "93",
                tags: ["pedestrianPath"],
                distance: 2.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "95": {
        x: 3,
        y: 24.5,
        tags: [],
        edges: [
            {
                end: "40",
                tags: ["pedestrianPath"],
                distance: 1.5,
                angle: -1.5707963267948966,
            },
            {
                end: "96",
                tags: ["pedestrianPath"],
                distance: 13,
                angle: 0,
            },
        ],
    },
    "96": {
        x: 16,
        y: 24.5,
        tags: [],
        edges: [
            {
                end: "38",
                tags: ["pedestrianPath"],
                distance: 1.8027756377319946,
                angle: -0.982793723247329,
            },
            {
                end: "97",
                tags: ["pedestrianPath"],
                distance: 2,
                angle: 0,
            },
            {
                end: "95",
                tags: ["pedestrianPath"],
                distance: 13,
                angle: 3.141592653589793,
            },
            {
                end: "99",
                tags: ["pedestrianPath"],
                distance: 2,
                angle: 1.5707963267948966,
            },
        ],
    },
    "97": {
        x: 18,
        y: 24.5,
        tags: [],
        edges: [
            {
                end: "38",
                tags: ["pedestrianPath"],
                distance: 1.8027756377319946,
                angle: -2.1587989303424644,
            },
            {
                end: "96",
                tags: ["pedestrianPath"],
                distance: 2,
                angle: 3.141592653589793,
            },
            {
                end: "100",
                tags: ["pedestrianPath"],
                distance: 2,
                angle: 1.5707963267948966,
            },
            {
                end: "98",
                tags: ["pedestrianPath"],
                distance: 13,
                angle: 0,
            },
        ],
    },
    "98": {
        x: 31,
        y: 24.5,
        tags: [],
        edges: [
            {
                end: "97",
                tags: ["pedestrianPath"],
                distance: 13,
                angle: 3.141592653589793,
            },
            {
                end: "37",
                tags: ["pedestrianPath"],
                distance: 1.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "99": {
        x: 16,
        y: 26.5,
        tags: ["pedestrianExit"],
        edges: [
            {
                end: "96",
                tags: ["pedestrianPath"],
                distance: 2,
                angle: -1.5707963267948966,
            },
        ],
    },
    "100": {
        x: 18,
        y: 26.5,
        tags: ["pedestrianEntrance"],
        edges: [
            {
                end: "97",
                tags: ["pedestrianPath"],
                distance: 2,
                angle: -1.5707963267948966,
            },
        ],
    },
    "101": {
        x: 3,
        y: 3.5,
        tags: ["botSpawn"],
        edges: [
            {
                end: "0",
                tags: ["botPath"],
                distance: 5,
                angle: 3.141592653589793,
            },
        ],
    },
    "102": {
        x: 2,
        y: 0,
        tags: ["botQueue"],
        edges: [
            {
                end: "2",
                tags: ["botPath", "carPath", "pedestrianPath"],
                distance: 1,
                angle: 0,
            },
        ],
    },
    "104": {
        x: 2,
        y: 2,
        tags: [],
        edges: [
            {
                end: "102",
                tags: ["botPath"],
                distance: 3.5,
                angle: -1.5707963267948966,
            },
        ],
    },
    "105": {
        x: -2,
        y: 2,
        tags: [],
        edges: [
            {
                end: "104",
                tags: ["botPath"],
                distance: 4,
                angle: 0,
            },
        ],
    },
    entrance: {
        x: 0,
        y: 0,
        tags: ["entrance"],
        edges: [
            {
                end: "102",
                tags: ["botPath", "carPath", "pedestrianPath"],
                distance: 2,
                angle: 0,
            },
        ],
    },
} as IParkingGraph;
